### ISSUE TITLE
Can craft items without the appropriate amount of materials

### ISSUE THREAD

**Issue by phyne** [gigaherz/SewingKit#2]
If you put enough materials into the sewingtable to craft a leather chestplate for instance with some leftover, you can craft the other pieces of leather armor because they've already popped up in the crafting menu, even if you don't have the required strips/sheets.

**Comment by gigaherz** [comment]
Hmm I'll take a look. I probably forgot to refresh the available recipes list on crafting.

**Comment by gigaherz** [comment]
Weirdly enough, I think both of your issue reports (this and #3) had the same root cause! I wasn't considering different stack sizes as different inputs! Only the item changes were triggering a check for recipes, which means

1. I wasn't updating the list after crafting, when only the counts changed.
2. I wasn't updating the list when inserting 1 by 1, when only the counts changed.

Oops!

**Comment by gigaherz** [comment]
Heya, v1.3.0 is up on curseforge, and should fix this issue.
